name: Move to Work Project

on: [push]

jobs:
  my-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Find my pull requests
        id: pull-requests
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const query = `{
              viewer {
                login
                pullRequests(first: 100, states: OPEN) {
                  edges {
                    node {
                      id
                    }
                  }
                }
              }
            }`
            const result = await github.graphql(query)
            return result.viewer.pullRequests

      - name: Add to project
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log("${{steps.pull-requests.outputs.result}}")
